project:
  type: website
  output-dir: docs
  resources: 
    - _img

website:
  title: "blog"
  site-url: https://ieien49.github.io/blog/
  navbar:
    left:
      - href: index.qmd
        text: Accueil
        icon: bi-house-door-fill
      - about.qmd
      - href: test.qmd
        text: Cartographie
        icon: bi-geo-alt-fill
    right:
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: https://macgraveur.github.io/mapage/sitemap.xml
  sidebar:
    style: "docked"
    search: true
format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true

editor: visual

