project:
  type: website
  output-dir: docs
  resources: 
    - _img

website:
  title: "blog"
  site-url: https://ieien49.github.io/blog/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: rss
        href: https://macgraveur.github.io/mapage/sitemap.xml
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

