project:
  type: website
  output-dir: docs
  resources: 
    - _img

website:
  title: "blog"
  site-url: https://ieien49.github.io/blog/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  announcement: 
1    icon: info-circle
2    dismissable: true
3    content: "**Alert** - this is some information that you should pay attention to"
4    type: primary
5    position: below-navbar

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

